name: First Workflow
on: workflow_dispatch
jobs:
  firts-job:
   runs-on: ubuntu-latest
   steps:
     - name: Print greeting
       run: |
           echo "Hello World"
           echo "Hello World v2"
     - name: Print good bye
       run: echo "Done - bye!"
